### ISSUE TITLE
Peer review 1 - kl222jy

### ISSUE THREAD

**Issue by kristofferlind** [afrxx09/afrxx09_1dv450#1]
# Peer review 1
## Installation

Korrekt beskrivning, inga problem.
## Säkerhet

ApiKeysController.destroy kontrollerar bara att användaren är inloggad, borde vara en kontroll att användaren tillhör nyckeln som ska tas bort eller är admin.

Har du funderat något över att användaren direkt kan generera en ny nyckel då admin tagit bort den? Jag gav inte användaren möjligheten alls, men tänker att användaren borde kunna göra det om det är användaren själv som tagit bort sin nyckel. Alternativt att användaren bara har möjlighet att generera om nyckel eller ta bort hela kontot.
## Kod

Inga kommentarer, finns ingen kod där det direkt behövs och jag är själv också riktigt dålig på att kommentera, men värt att sträva efter att bli bättre på. Finns ett stavfel på singed_in_user, annars väldigt bra metod och variabelnamn. I UsersController.update skulle du kunna lyfta ut render 'show' och på så vis bli av med else-grenen och då även kunna göra om if-satsen till en oneliner, det är väl dock lite av en smaksak.
## Design

Riktigt kul att se en helt egen design istället för alla designramverk. Menyknapparna borde följa mitten eller botten istället för toppen och det skulle nog behövas lite mer luft mellan header och innehåll. Det skulle också behövas lite mer kontrast mellan text och bakgrund för notifikationer. Ser annars riktigt trevligt ut, tack för att jag fick se lite nya färger =)

Lycka till med projektet!

**Comment by afrxx09** [comment]
Att ta kontrollera användaren/admin vid borttagning av nyckel hade jag helt glömt, tack för den påminnelsen.
En användare kan skapa en ny nyckel direkt efter att de tagit bort den, man kan även generera ny nyckel som skriver över den befintliga.

Väljer alltid att aktivt inte använda bootstrap, just desingne på menyn har jag inte lagt mycket kärlek på så den "blev vad den blev" när den väl var på plats =)

Tack för din input

**Comment by 1dv450** [comment]
:+1:  Bra feedback och kommentarer
