### ISSUE TITLE
Peer Review 1 - ja222qm

### ISSUE THREAD

**Issue by juhaniaa** [afrxx09/afrxx09_1dv450#2]
## Första intryck

Installationen var tydlig och allt fungerade utan problem. Din lösning känns välarbetad och genomtänkt. Positivt med lite styling och "remember me"- funktionalitet. Tydlig namngivning av metoder o parametrar gör det enklare att följa koden, dock skulle några kommentarer underlätta detta ännu mera.
## Admin

Är det ett medvetet val att låta admin generera en API nyckel åt sig? Känns som att det vore bättre att ha en tydlig uppdelning mellan user och admin. I övrigt fungerar även detta väldigt bra.
## Formulär

Bra med templates för formulär när det gäller både felhantering och inloggning. Kanske kunde även formuläret för registrering/uppdatering brytas ut till en template, då den delen i user/index.html.erb och user/show.html.erb är nästan identisk.
## Övrigt

Såg att du hade skrivit en del tester vilket är positivt, dessa fick jag dock inte att gå igenom med endast rake test. Kanske kunde ha skrivit en instruktion för hur man går tillväga där. Totalt sett har du gjort ett mycket bra arbete med din registreringsapplikation som ger ett proffsigt helhetsintryck.

// Juhani Aavanen - ja222qm

**Comment by afrxx09** [comment]
Testerna körde jag med i början, men slutade lite med dem efter hand så de är nog inte "up to date".

Formuläret för registrering och uppdatering är tänkt att skilja sig mer senare då jag vill lägga till mer information på användaren men inte tvinga dem att skriva in all den informationen redan vid registrering.

Att admins har nycklar har jag inte riktigt bestämt mig om ännu men det lutar åt att det ska försvinna för dem så deras enda uppgift är att "administrera".

Tack för din input!
